In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction import CountVectorizer

ModuleNotFoundError: No module named 'sklearn'

In [2]:
pip install seaborn


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'D:\Python\python.exe -m pip install --upgrade pip' command.


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction import CountVectorizer

In [3]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'D:\Python\python.exe -m pip install --upgrade pip' command.


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction import CountVectorizer

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction import CountVectorizer

ModuleNotFoundError: No module named 'sklearn'

In [6]:
!pip install scikit-learn

You should consider upgrading via the 'D:\Python\python.exe -m pip install --upgrade pip' command.


In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction import CountVectorizer

ImportError: cannot import name 'CountVectorizer' from 'sklearn.feature_extraction' (D:\Python\lib\site-packages\sklearn\feature_extraction\__init__.py)

In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
df=pd.read_csv("E:/Sports/spam.csv",encoding="latin1")

In [11]:
df.head(n=10)

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [12]:
df.shape

(5572, 5)

In [13]:
np.unique(df['class'])

array(['ham', 'spam'], dtype=object)

In [15]:
np.unique(df['message'])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [16]:
x=df['message'].values
y=df['class'].values
cv=CountVectorizer()

x=cv.fit_transform(x)
v=x.toarray()
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
df = df.reindex(['message','class','Unnamed:2','Unnamed:3','Unnamed:4'], axis=1) 

In [24]:
print(df)


      message class  Unnamed:2  Unnamed:3  Unnamed:4
0         NaN   ham        NaN        NaN        NaN
1         NaN   ham        NaN        NaN        NaN
2         NaN  spam        NaN        NaN        NaN
3         NaN   ham        NaN        NaN        NaN
4         NaN   ham        NaN        NaN        NaN
...       ...   ...        ...        ...        ...
5567      NaN  spam        NaN        NaN        NaN
5568      NaN   ham        NaN        NaN        NaN
5569      NaN   ham        NaN        NaN        NaN
5570      NaN   ham        NaN        NaN        NaN
5571      NaN   ham        NaN        NaN        NaN

[5572 rows x 5 columns]


In [25]:
train_x=x[:4180]
train_y=y[:4180]

test_x=x[4180:]
test_y=y[4180:]

In [26]:
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(train_x,train_y)

y_pred_train=bnb.predict(train_x)
y_pred_test=bnb.predict(test_x)

In [28]:
print(bnb.score(train_x,train_y)*100)
print(bnb.score(test_x,test_y)*100)

98.70813397129187
98.20402298850574


In [30]:
from sklearn.metrics import classification_report
print(classification_report(train_y,y_pred_train))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3615
        spam       0.99      0.91      0.95       565

    accuracy                           0.99      4180
   macro avg       0.99      0.95      0.97      4180
weighted avg       0.99      0.99      0.99      4180



In [31]:
from sklearn.metrics import classification_report
print(classification_report(test_y,y_pred_test))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1210
        spam       0.99      0.87      0.93       182

    accuracy                           0.98      1392
   macro avg       0.99      0.93      0.96      1392
weighted avg       0.98      0.98      0.98      1392

